version: "3.8"

services:
  mc:
    container_name: "mc"
    build: "./"
    tty: true
    stdin_open: true
    ports:
      - "25565:25565" # Server
      # - "25575:25575" # RCON
      - "80:80"       # HTTP
      - "22:22"       # SSH
    environment:
      EULA: "TRUE"
      TYPE: "FABRIC"
      VERSION: "1.20.1"
      UMASK: "0007"
      # DEBUG: "true" # Disables the Minecraft server and runs an openssh server in the foreground
    volumes:
      - "./data:/data"
      - "./mods:/mods"
    restart: "no"
